---
apiVersion: v1
kind: Service
metadata:
  name: db
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: db
    port: 8080 
  selector:
    app: toydb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db 
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db 
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
        - name: db 
          image: dgraph/standalone:v20.07.2 
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: db 
              containerPort: 8080
              protocol: TCP
          env:
            - name: DGRAPH_ALPHA_GRAPHQL_EXTENSIONS
              value: "true"
          volumeMounts:
            - mountPath: /dgraph
              name: data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data 
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
